my_orleans:
    resource: "@MyOrleansBundle/Controller/"
    type:     annotation
    prefix:   /site



blog:
    resource: "@BlogBundle/Controller/"
    type:     annotation
    prefix:   /blog

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


