<?php

namespace MyOrleansBundle\Repository;

/**
 * AncienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AncienRepository extends \Doctrine\ORM\EntityRepository
{
}
