<?php

namespace MyOrleansBundle\Repository;

/**
 * ChiffreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChiffreRepository extends \Doctrine\ORM\EntityRepository
{
}
