<?php

namespace MyOrleansBundle\Repository;

/**
 * NormeThermiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NormeThermiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
