<?php

namespace MyOrleansBundle\Repository;

/**
 * PlaquetteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaquetteRepository extends \Doctrine\ORM\EntityRepository
{
}
