<?php

namespace MyOrleansBundle\Repository;

/**
 * ResidenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResidenceRepository extends \Doctrine\ORM\EntityRepository
{
    public function simpleSearch($ville, $type)
    {
        $qb = $this->createQueryBuilder('r');

        if (!empty($ville)) {
            $qb->andWhere('v.nom LIKE :ville')
                ->andWhere('fl.statut = true')
                ->setParameter('ville', '%'.$ville.'%')
                ->join('r.flats', 'fl')
                ->join('r.ville', 'v')
                ->orderBy('r.tri', 'ASC');
        }

        if (!empty($type)) {
            $qb->andWhere('t.nom = :type')
                ->andWhere('f.statut = true')
                ->setParameter('type', $type)
                ->join('r.flats', 'f')
                ->join('f.typeLogement', 't')
                ->orderBy('r.tri', 'ASC');
        }

        return $qb->getQuery()->getResult();
    }


    public function completeSearch($data)
    {
        $qb = $this->createQueryBuilder('r');

        if (!empty($data['ville'])) {
            $qb->andWhere('v.nom LIKE :ville')
                ->andWhere('flt.statut = true')
                ->setParameter('ville', '%'.$data['ville'].'%')
                ->join('r.ville', 'v')
                ->join('r.flats', 'flt')
                ->orderBy('r.tri', 'ASC');
        }


        if (!empty($data['typeLogement'])) {
            $qb->andWhere('t.id IN(:type)')
                ->andWhere('f.statut = true')
                ->setParameter('type', $data['typeLogement'])
                ->join('r.flats', 'f')
                ->join('f.typeLogement', 't')
                ->orderBy('r.tri', 'ASC');
        }


        if (!empty($data['budgetMin'])) {
            $qb->andWhere('ft.prix >= :budgetMin')
                ->andWhere('ft.statut = true')
                ->setParameter('budgetMin', $data['budgetMin'])
                ->join('r.flats', 'ft')
                ->orderBy('r.tri', 'ASC');
        }

        if (!empty($data['budgetMax'])) {
            $qb->andWhere('fts.prix <= :budgetMax ')
                ->andWhere('fts.statut = true')
                ->setParameter('budgetMax', $data['budgetMax'])
                ->join('r.flats', 'fts')
                ->orderBy('r.tri', 'ASC');
        }

        return $qb->getQuery()->getResult();
    }


    public function suggestResidence($idResidence)
    {
            $qb = $this->createQueryBuilder('r')
                ->where('r.id NOT IN(:idResidence)')
                ->setParameter('idResidence', $idResidence)
                ->andWhere('r.favoris = true')
                ->orderBy('r.tri', 'ASC')
                ->setMaxResults(4);

            return $qb->getQuery()->getResult();
    }

    public function findAllLimit()
    {
        $qb = $this->createQueryBuilder('r')
            ->orderBy('r.id','DESC')
            ->setMaxResults(6);
        return $qb->getQuery()->getResult();

    }

    public function findOneFav()
    {
        $qb = $this->createQueryBuilder('r')
            ->where('r.favoris = 1')
            ->orderBy('r.tri', 'ASC')
            ->setMaxResults(1);
         return $qb->getQuery()->getResult();
    }

    public function findTwoFav()
    {
        $qb = $this->createQueryBuilder('r')
            ->where('r.favoris = 1')
            ->orderBy('r.tri', 'ASC')
            ->setMaxResults(2);
        return $qb->getQuery()->getResult();
    }
}

