<?php

namespace MyOrleansBundle\Repository;

/**
 * TrimestreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrimestreRepository extends \Doctrine\ORM\EntityRepository
{
}
